"""empty message

Revision ID: c3eac23c0a5d
Revises: cb9d1c5d9775
Create Date: 2023-11-24 16:48:35.482645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3eac23c0a5d'
down_revision = 'cb9d1c5d9775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cocktail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('drink_name', sa.String(), nullable=False),
    sa.Column('glass_type', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('drink_type', sa.Boolean(), nullable=False),
    sa.Column('ingredient_1', sa.String(), nullable=False),
    sa.Column('measure_1', sa.String(), nullable=False),
    sa.Column('ingredient_2', sa.String(), nullable=False),
    sa.Column('measure_2', sa.String(), nullable=False),
    sa.Column('ingredient_3', sa.String(), nullable=True),
    sa.Column('measure_3', sa.String(), nullable=True),
    sa.Column('ingredient_4', sa.String(), nullable=True),
    sa.Column('measure_4', sa.String(), nullable=True),
    sa.Column('ingredient_5', sa.String(), nullable=True),
    sa.Column('measure_5', sa.String(), nullable=True),
    sa.Column('ingredient_6', sa.String(), nullable=True),
    sa.Column('measure_6', sa.String(), nullable=True),
    sa.Column('ingredient_7', sa.String(), nullable=True),
    sa.Column('measure_7', sa.String(), nullable=True),
    sa.Column('ingredient_8', sa.String(), nullable=True),
    sa.Column('measure_8', sa.String(), nullable=True),
    sa.Column('ingredient_9', sa.String(), nullable=True),
    sa.Column('measure_9', sa.String(), nullable=True),
    sa.Column('ingredient_10', sa.String(), nullable=True),
    sa.Column('measure_10', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cocktail')
    # ### end Alembic commands ###
